export enum AuditAction {
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  CREATE_GAME = 'CREATE_GAME',
  UPDATE_GAME = 'UPDATE_GAME',
  DELETE_GAME = 'DELETE_GAME',
  CREATE_PATCH = 'CREATE_PATCH',
  UPLOAD_PATCH = 'UPLOAD_PATCH',
  PUBLISH_PATCH = 'PUBLISH_PATCH',
  REPLACE_PATCH = 'REPLACE_PATCH',
  FORCE_UPDATE_LAUNCHER = 'FORCE_UPDATE_LAUNCHER',
  DELETE_R2_OBJECTS = 'DELETE_R2_OBJECTS',
}

export enum AuditEntityType {
  GAME = 'GAME',
  PATCH_VERSION = 'PATCH_VERSION',
  LAUNCHER = 'LAUNCHER',
  SYSTEM = 'SYSTEM',
}
